name: auto build engine

on: 
  release:
    types: [published]
  #schedule:
  #  - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install build depedencies
        run: |
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
  upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Build firmware
        run: |
          git clone https://github.com/immortalwrt/immortalwrt
          pushd immortalwrt
          git checkout 516c0d7b0cdc6245508411f04d6cb508a1c66936
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget --no-check-certificate -O .config https://raw.githubusercontent.com/ActiveIce/CT3003/master/config 
          yes "" | make oldconfig
          make download -j$(nproc)
          make -j$(nproc)
          popd

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: firmware
          path: |
            ./immortalwrt/bin/targets/mediatek/filogic/immortalwrt-mediatek-filogic-cetron_ct3003-ubootmod-squashfs-factory.bin
            ./immortalwrt/bin/targets/mediatek/filogic/immortalwrt-mediatek-filogic-cetron_ct3003-ubootmod-squashfs-sysupgrade.bin

  push:
    needs: build
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Clean
      run: |
        rm immortalwrt-mediatek-filogic-cetron_ct3003-ubootmod-squashfs-factory.bin
        rm immortalwrt-mediatek-filogic-cetron_ct3003-ubootmod-squashfs-sysupgrade.bin
    
    - name: Download firmware
      uses: actions/download-artifact@main
      with:
        name: firmware
        path: ./
    
    - name: Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan new_branch
        git add -A
        git commit -am "update new file"
        git branch -D master
        git branch -m master
        git push origin master --force
